/**
 * Composable for managing SEO meta tags and structured data
 * Provides reusable defaults and helper functions for consistent SEO implementation
 */

import { useHead } from '@unhead/vue'
import { computed, toValue } from 'vue'

/**
 * Escape HTML special characters to prevent XSS in user-provided content
 * @param {string} str - String to sanitize
 * @returns {string} Sanitized string with HTML entities escaped
 */
function escapeHtml(str) {
  if (typeof str !== 'string') return str
  
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

/**
 * Generate comprehensive SEO meta tags using useHead
 * @param {Object} options - SEO configuration options
 * @param {string} options.title - Page title
 * @param {string} options.description - Page description
 * @param {string} options.url - Canonical URL
 * @param {string} [options.image] - Social sharing image URL
 * @param {string} [options.imageWidth='1200'] - Image width for OG/Twitter
 * @param {string} [options.imageHeight='630'] - Image height for OG/Twitter
 * @param {string} [options.imageAlt] - Image alt text (defaults to title)
 * @param {string} [options.type='website'] - Open Graph type
 * @param {string} [options.keywords] - Comma-separated keywords
 * @param {Array<Object>} [options.structuredData] - Array of structured data objects
 * @param {Object} [options.meta] - Additional meta tags to merge
 * @param {Object} [options.link] - Additional link tags to merge
 * @param {string} [options.robots='index, follow'] - Robots meta content
 */
// Branded 1200x630 social-share image (generated by scripts/generate-og-image.js).
// Used as the default whenever a page doesn't supply its own image.
const DEFAULT_OG_IMAGE = 'https://cloud.runonflux.com/images/og-image.png'

export function useSEO(options) {
  const {
    title,
    description,
    url,
    image = DEFAULT_OG_IMAGE,
    imageWidth,
    imageHeight,
    imageAlt,
    type = 'website',
    keywords = '',
    structuredData = [],
    meta = [],
    link = [],
    robots = 'index, follow',
  } = options

  // Only declare og:image dimensions when we actually know them. The default
  // share image is a known 1200x630; page-supplied images (e.g. app icons) are
  // arbitrary sizes, so we omit the dimensions and let platforms detect them
  // rather than advertise wrong values.
  const usesDefaultImage = options.image === undefined
  const ogImageWidth = imageWidth ?? (usesDefaultImage ? '1200' : undefined)
  const ogImageHeight = imageHeight ?? (usesDefaultImage ? '630' : undefined)

  // Sanitize user-provided content to prevent XSS.
  // title/description/keywords may be plain strings or reactive refs —
  // dynamic pages (e.g. marketplace/[id]) pass computed values — so resolve
  // and escape inside a computed to stay reactive and keep escaping correct.
  const safeTitle = computed(() => escapeHtml(toValue(title)))
  const safeDescription = computed(() => escapeHtml(toValue(description)))
  const safeKeywords = computed(() => escapeHtml(toValue(keywords)))

  // Use title as default alt text if not provided
  const imgAlt = computed(() => escapeHtml(toValue(imageAlt) || toValue(title)))

  // Default meta tags
  const defaultMeta = [
    {
      name: 'description',
      content: safeDescription,
    },
    {
      name: 'author',
      content: 'Flux Network',
    },
    {
      name: 'robots',
      content: robots,
    },

    // Open Graph
    { property: 'og:title', content: safeTitle },
    { property: 'og:description', content: safeDescription },
    { property: 'og:image', content: image },
    ...(ogImageWidth ? [{ property: 'og:image:width', content: ogImageWidth }] : []),
    ...(ogImageHeight ? [{ property: 'og:image:height', content: ogImageHeight }] : []),
    { property: 'og:image:alt', content: imgAlt },
    { property: 'og:url', content: url },
    { property: 'og:type', content: type },
    { property: 'og:site_name', content: 'FluxCloud' },
    { property: 'og:locale', content: 'en_US' },

    // Twitter Card
    { name: 'twitter:card', content: 'summary_large_image' },
    { name: 'twitter:title', content: safeTitle },
    { name: 'twitter:description', content: safeDescription },
    { name: 'twitter:image', content: image },
    { name: 'twitter:image:alt', content: imgAlt },
    { name: 'twitter:site', content: '@RunOnFlux' },
    { name: 'twitter:creator', content: '@RunOnFlux' },
  ]

  // Add keywords if provided
  if (toValue(keywords)) {
    defaultMeta.push({
      name: 'keywords',
      content: safeKeywords,
    })
  }

  // Default link tags
  const defaultLink = [
    { rel: 'canonical', href: url },
  ]

  // Generate structured data scripts (reactive computed)
  // Handle both raw arrays and computed refs - wrap in computed for reactivity
  const scripts = computed(() => {
    const data = structuredData?.value !== undefined ? structuredData.value : structuredData
    
    return data && data.length > 0
      ? [
        {
          type: 'application/ld+json',
          innerHTML: JSON.stringify(data),
        },
      ]
      : []
  })

  useHead({
    title: safeTitle,
    meta: [...defaultMeta, ...meta],
    link: [...defaultLink, ...link],
    script: scripts, // Pass computed ref so useHead can track changes
  })
}

/**
 * Generate Organization structured data
 * @returns {Object} Organization schema
 */
export function generateOrganizationSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    'name': 'Flux Network',
    'url': 'https://cloud.runonflux.com',
    'logo': {
      '@type': 'ImageObject',
      'url': 'https://cloud.runonflux.com/images/logo.png',
    },
    'description': 'Decentralized Web3 cloud infrastructure powered by FluxNodes worldwide',
    'sameAs': [
      'https://twitter.com/RunOnFlux',
      'https://github.com/RunOnFlux',
    ],
  }
}

/**
 * Generate Breadcrumb structured data
 * @param {Array<Object>} items - Breadcrumb items [{name: 'Home', url: '...'}]
 * @returns {Object} BreadcrumbList schema
 */
export function generateBreadcrumbSchema(items) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    'itemListElement': items.map((item, index) => ({
      '@type': 'ListItem',
      'position': index + 1,
      'name': item.name,
      'item': item.url,
    })),
  }
}

/**
 * Generate Product structured data
 * @param {Object} product - Product information
 * @param {string} product.name - Product name
 * @param {string} product.description - Product description
 * @param {string} product.image - Product image URL
 * @param {string} product.url - Product URL
 * @param {number} product.price - Product price
 * @param {string} [product.currency='USD'] - Price currency
 * @param {string} [product.availability='https://schema.org/InStock'] - Availability status
 * @returns {Object} Product schema
 */
export function generateProductSchema(product) {
  const {
    name,
    description,
    image,
    url,
    price,
    currency = 'USD',
    availability = 'https://schema.org/InStock',
  } = product

  return {
    '@context': 'https://schema.org',
    '@type': 'Product',
    'name': name,
    'description': description,
    'image': image,
    'url': url,
    'offers': {
      '@type': 'Offer',
      'price': price,
      'priceCurrency': currency,
      'availability': availability,
      'url': url,
    },
  }
}

/**
 * Generate WebApplication structured data
 * @param {Object} app - Application information
 * @param {string} app.name - Application name
 * @param {string} app.description - Application description
 * @param {string} app.url - Application URL
 * @param {string} app.image - Application image URL
 * @param {Array<string>} [app.features] - Feature list
 * @param {Object} [app.offers] - Offer information {lowPrice, highPrice}
 * @returns {Object} WebApplication schema
 */
export function generateWebApplicationSchema(app) {
  const {
    name,
    description,
    url,
    image,
    features = [],
    offers,
  } = app

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    'name': name,
    'applicationCategory': 'BusinessApplication',
    'operatingSystem': 'Web',
    'description': description,
    'url': url,
    'image': image,
    'provider': {
      '@type': 'Organization',
      'name': 'Flux Network',
      'url': 'https://runonflux.com',
    },
  }

  if (features.length > 0) {
    schema.featureList = features
  }

  if (offers) {
    schema.offers = {
      '@type': 'AggregateOffer',
      'priceCurrency': 'USD',
      'lowPrice': offers.lowPrice || '0.99',
      'highPrice': offers.highPrice || '500',
    }
  }

  return schema
}

/**
 * Generate FAQPage structured data
 * @param {Array<Object>} faqs - FAQ items [{question: '...', answer: '...'}]
 * @returns {Object} FAQPage schema
 */
export function generateFAQSchema(faqs) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    'mainEntity': faqs.map(faq => ({
      '@type': 'Question',
      'name': faq.question,
      'acceptedAnswer': {
        '@type': 'Answer',
        'text': faq.answer,
      },
    })),
  }
}

/**
 * Generate ItemList structured data (useful for marketplace listings)
 * @param {Array<Object>} items - List items [{name: '...', url: '...', description: '...', price: 0}]
 * @param {string} [listName] - Name of the list
 * @returns {Object} ItemList schema
 */
export function generateItemListSchema(items, listName) {
  const schema = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    'itemListElement': items.map((item, index) => ({
      '@type': 'ListItem',
      'position': index + 1,
      'item': {
        '@type': 'SoftwareApplication',
        'name': item.name,
        'url': item.url,
        'description': item.description,
        'applicationCategory': 'WebApplication',
        'operatingSystem': 'Web',
        'offers': {
          '@type': 'Offer',
          'price': item.price || 0,
          'priceCurrency': 'USD',
          'availability': 'https://schema.org/InStock',
        },
      },
    })),
  }

  if (listName) {
    schema.name = listName
  }

  return schema
}

/**
 * Generate SoftwareApplication structured data
 * @param {Object} software - Software information
 * @param {string} software.name - Software name
 * @param {string} software.description - Software description
 * @param {string} software.url - Software URL
 * @param {string} software.image - Software image URL
 * @param {Object} [software.offers] - Pricing information {price, currency, availability}
 * @param {string} [software.applicationCategory] - Application category (e.g., 'GameServer', 'BusinessApplication')
 * @param {string} [software.operatingSystem] - Operating system (e.g., 'Linux', 'Web')
 * @param {Array<string>} [software.features] - List of features
 * @param {Object} [software.aggregateRating] - Rating information {ratingValue, reviewCount, bestRating}
 * @param {Object} [software.provider] - Provider information {name, url}
 * @returns {Object} SoftwareApplication schema
 */
export function generateSoftwareApplicationSchema(software) {
  const {
    name,
    description,
    url,
    image,
    offers,
    applicationCategory = 'BusinessApplication',
    operatingSystem = 'Web',
    features = [],
    aggregateRating,
    provider,
  } = software

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    'name': name,
    'description': description,
    'url': url,
    'image': image,
    'operatingSystem': operatingSystem,
    'applicationCategory': applicationCategory,
    'provider': provider || {
      '@type': 'Organization',
      'name': 'Flux Network',
      'url': 'https://runonflux.com',
    },
  }

  // Add offers if provided
  if (offers) {
    schema.offers = {
      '@type': 'Offer',
      'price': offers.price || '0',
      'priceCurrency': offers.currency || 'USD',
      'availability': offers.availability || 'https://schema.org/InStock',
      'url': url,
    }
  }

  // Add features if provided
  if (features.length > 0) {
    schema.featureList = features
  }

  // Add aggregate rating only when BOTH a real rating value and a real count
  // exist. Never fabricate a rating or review count: Google treats invented
  // ratings as a structured-data policy violation and may issue a manual action.
  const ratingValue = aggregateRating?.ratingValue
  const ratingCount = aggregateRating?.reviewCount ?? aggregateRating?.ratingCount
  if (ratingValue != null && ratingCount != null) {
    schema.aggregateRating = {
      '@type': 'AggregateRating',
      'ratingValue': ratingValue,
      'reviewCount': ratingCount,
      'bestRating': aggregateRating.bestRating || '5',
      'worstRating': aggregateRating.worstRating || '1',
    }
  }

  return schema
}

/**
 * Generate Article structured data with timestamps
 * @param {Object} article - Article information
 * @param {string} article.headline - Article headline/title
 * @param {string} article.description - Article description
 * @param {string} article.url - Article URL
 * @param {string} article.image - Article image URL
 * @param {string} [article.datePublished] - ISO date string for publication date
 * @param {string} [article.dateModified] - ISO date string for last modification date
 * @param {string} [article.author] - Author name (defaults to 'Flux Network')
 * @returns {Object} Article schema
 */
export function generateArticleSchema(article) {
  const {
    headline,
    description,
    url,
    image,
    datePublished,
    dateModified,
    author = 'Flux Network',
  } = article

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    'headline': headline,
    'description': description,
    'url': url,
    'image': image,
    'author': {
      '@type': 'Organization',
      'name': author,
      'url': 'https://runonflux.com',
    },
    'publisher': {
      '@type': 'Organization',
      'name': 'Flux Network',
      'logo': {
        '@type': 'ImageObject',
        'url': 'https://cloud.runonflux.com/images/logo.png',
      },
    },
  }

  if (datePublished) {
    schema.datePublished = datePublished
  }

  if (dateModified) {
    schema.dateModified = dateModified
  }

  return schema
}

/**
 * Set meta robots to noindex for private pages
 * Useful for dashboard, admin, and authenticated pages
 */
export function useSEONoIndex() {
  useHead({
    meta: [
      {
        name: 'robots',
        content: 'noindex, nofollow',
      },
    ],
  })
}

/**
 * Coordinate SEO prerendering for pages whose title, meta description, or
 * JSON-LD structured data depend on data fetched asynchronously after mount.
 *
 * Such a page calls usePrerenderReady() during setup and invokes the returned
 * markReady() once that data has resolved (or failed). scripts/prerender.js
 * waits for this signal before snapshotting the static HTML, so loading-state
 * metadata (generic titles, empty schema) is never baked into the prerendered
 * output.
 *
 * Pages with no async SEO data do not need this — the prerender script treats
 * the absence of the data-prerender-pending attribute as "ready".
 *
 * @returns {{ markReady: () => void }}
 */
export function usePrerenderReady() {
  const PENDING_ATTR = 'data-prerender-pending'

  if (typeof document !== 'undefined') {
    document.documentElement.setAttribute(PENDING_ATTR, 'true')
  }

  let settled = false

  const markReady = () => {
    if (settled || typeof document === 'undefined') return
    settled = true
    document.documentElement.setAttribute(PENDING_ATTR, 'false')
  }

  return { markReady }
}
